version: '3.8'

services:
  llm-engine:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/models/sentiment_model_metal.mlpackage
      - TOKENIZER_NAME=distilbert-base-uncased
      - BATCH_SIZE=32
      - NUM_THREADS=4
    deploy:
      resources:
        reservations:
          devices:
            - driver: apple-gpu
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
